#pragma once

// Relay allocation / session table (ADR-001 §3.3, §3.6.2).
//
// The relay is a THIN BLIND-FORWARD path: it shuttles opaque Noise ciphertext
// between two endpoints that could not hole-punch, keyed by an allocation /
// session token. It NEVER decrypts — it has zero knowledge of media keys
// (§3.6.2). This table is the relay's only state: token -> {two legs, byte
// counters, last activity} so a datagram arriving on one leg can be forwarded
// to the other.
//
// Allocation model (mirrors the idea of a TURN allocation, but proprietary and
// minimal — coturn/eturnal are only for the STANDARDS-TURN web-client path,
// §3.3): the rendezvous server (or a peer) requests an allocation; the relay
// returns a token + its public endpoint; each peer then sends its Noise traffic
// to that endpoint tagged with the token, and the relay learns each peer's
// source address from the first datagram on each leg (symmetric to ICE
// candidate discovery) and pairs them.
//
// Interface + in-memory stub. A real multi-region/anycast deployment shards
// this across nodes with consistent token routing + health/reselection
// (§3.3 / Risk #6). TODO(ADR §3.3): real distributed allocation backend.

#include <cstdint>
#include <memory>
#include <optional>
#include <string>

#include "core/common/types.h"
#include "server/common/net.h"

namespace redesk::server::relay {

// Opaque session/allocation token. Short, unguessable in the real build
// (generated by the rendezvous or the relay via libsodium randombytes); the
// stub uses a monotonic counter string. It is the ONLY thing the relay routes
// on — it carries no key material.
using SessionToken = std::string;

inline constexpr std::size_t kTokenLen = 16; // 128-bit token in the real build

// One of the two legs of a relayed session. `bound` flips true once we have
// seen a datagram from this leg and learned its source endpoint.
struct Leg {
    net::Endpoint endpoint;
    bool bound = false;
    std::uint64_t bytes_forwarded = 0;
};

// A relayed session: two legs + bookkeeping. Forwarding is symmetric — a packet
// from leg A goes to leg B and vice-versa, verbatim, encrypted end-to-end.
struct Allocation {
    SessionToken token;
    Leg a;
    Leg b;
    std::int64_t created_unix_s = 0;
    std::int64_t last_activity_unix_s = 0;

    bool fully_bound() const { return a.bound && b.bound; }
};

// Abstract allocation table. Thread-safe in the provided stub.
class AllocationTable {
public:
    virtual ~AllocationTable() = default;

    // Create a new allocation for `token` (idempotent: returns the existing one
    // if the token is already allocated). now_unix_s seeds the timestamps.
    virtual Status allocate(const SessionToken& token, std::int64_t now_unix_s) = 0;

    // A datagram for `token` arrived from `src`. Binds `src` to whichever leg it
    // matches (or the first free leg), updates activity, and returns the OTHER
    // leg's endpoint to forward to — or nullopt if the peer leg isn't bound yet
    // (drop until both sides have spoken). Unknown token => InvalidArgument.
    virtual Result<net::Endpoint> route(const SessionToken& token, const net::Endpoint& src,
                                        std::size_t bytes, std::int64_t now_unix_s) = 0;

    // Drop allocations idle longer than ttl_seconds. Returns count removed.
    virtual std::size_t expire(std::int64_t now_unix_s, std::int64_t ttl_seconds) = 0;

    virtual std::size_t size() const = 0;
};

std::unique_ptr<AllocationTable> make_in_memory_allocation_table();

} // namespace redesk::server::relay
